<?xml version="1.0"?>
<robot name="demo_pole" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="pole_radius" value="0.05"/>
  <xacro:property name="pole_length" value="1.25"/>
  <xacro:property name="pole_mass" value="1"/>
  <xacro:property name="pole_connect_offset" value="0.5"/>
  
  <xacro:property name="string_radius" value="0.01"/>
  <xacro:property name="string_length" value="${pole_length/4}"/>
  <xacro:property name="string_mass" value="0.1"/>

  <xacro:property name="apple_radius" value="0.06"/>
  <xacro:property name="apple_mass" value="1"/>

<!-- Pole base -->
  <link name ="pole_base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${pole_radius}" length="${pole_length}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${pole_radius}" length="${pole_length}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${pole_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name ="pole_connect_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${pole_radius}" length="${pole_length/2}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${pole_radius}" length="${pole_length/2}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${pole_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name ="string_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${string_radius}" length="${string_length}" />
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${string_radius}" length="${string_length}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${string_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="apple_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${apple_radius}"/>
    </geometry>
    <material name="red"/>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${apple_radius}"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="${apple_mass}"/>
    <origin xyz="0 0 0"/>
    <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
  </inertial>
</link>

  <joint name="pole_base_joint" type="fixed">
    <parent link="world"/>
    <child link="pole_base_link"/>
    <origin xyz="-${pole_connect_offset} 0.75 ${pole_length/2}" rpy="0 0 0"/>
  </joint>

  <joint name="pole_connect_joint" type="fixed">
    <parent link="pole_base_link"/>
    <child link="pole_connect_link"/>
    <origin xyz="${pole_length/4 - pole_radius} 0 ${pole_length/2}" rpy="0 ${pi/2} 0"/>
  </joint>

  <joint name="string_joint" type="fixed">
    <parent link="pole_connect_link"/>
    <child link="string_link"/>
    <origin xyz="${string_length/2} 0 ${pole_length/5}" rpy="0 ${pi/2} 0"/>
  </joint>

  <joint name="apple_joint" type="fixed">
    <parent link="string_link"/>
    <child link="apple_link"/>
    <origin xyz="0 0 ${string_length/2}" rpy="0 0 0"/>
  </joint>

</robot>
