/**:
    ros__parameters:
      camera_name: "ArduCam_IMX477"
      video_device: "/dev/video2"
      framerate: 100.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 1280
      image_height: 960
      camera_info_url: "package://ball_detection/config/arducam_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      exposure: 100
      focus: -1